/*指挥官*/
var commander={
  notebook:{
    orbitstatus:[false,false,false,false]
  },
  createSpaceShip:function(orbitId){
    if(this.notebook.orbitstatus[orbitId]){
      log("轨道"+(orbitId+1)+"上已经存在飞船","blue");
      return;
    }
    this.notebook.orbitstatus[orbitId]=true;
    log("在轨道"+(orbitId+1)+"上创建飞船！","yellow");
    spaceManager.Mediator.createSpaceShip(orbitId);
  },
  start:function(orbitId){
    log("向轨道"+(orbitId+1)+"发送开始飞行命令!","yellow");
    spaceManager.Mediator.sendMessage({
      id:orbitId,
      command:'start'
    });
  },
  stop:function(orbitId){
    log("向轨道"+(orbitId+1)+"发送停止飞行指令!","yellow");
    spaceManager.Mediator.sendMessage({
      id:orbitId,
      command:'stop'
    });
  },
  destroy:function(orbitId){
    log("向轨道"+(orbitId+1)+"发送自动销毁指令！","yellow");
    this.notebook.orbitstatus[orbitId]=false;
    spaceManager.Mediator.sendMessage({
      id:orbitId,
      command:'destroy'
    });
  },
  setRate:function(orbitId,rate){
    log("向轨道"+(orbitId+1)+"发送速度设置指令！","yellow");
    spaceManager.Mediator.sendMessage({
      id:orbitId,
      command:setRate,
      value:rate
    });
  },
}